apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: hello-param
spec:
  params:
    - name: param1
      description: The first parameter
      type: string
      default: "/foo/bar"
  results:
    - name: result1
      description: The first result
      type: string
  image: zshusers/zsh:4.3.15
  script: |
    #!/usr/bin/env zsh
    echo -n hello HARDCODE | tee $(results.result1.path)
